


name: test_math_dev

on:
	push:
		branches: [ dev ]
	pull_request:
		branches: [ dev ]

env:
	CARGO_TERM_COLOR: always

jobs:
	build:

		runs-on: ubuntu-latest
		statergy:
			matrix:
				toolchain:
					- stable
					- beta
					- nightly

		steps:
		- uses: actions/checkout@v3
		- run: rustup update ${{ matrix.toolchain }} && rustup default &{{ matrix.toolchain }}
		- name: Run tests
			run: cargo test --verbose


